### ISSUE TITLE
Tilted curve issue when using zhang fit

### ISSUE THREAD

**Issue by sai7842** [StatguyUser/BaselineRemoval#18]
Hi,

I am currently using zhng fit model for the values mentioned below.
6441.98,6383.192,6325.8344,6269.60528,6214.487936,6159.418643,6105.581316,6053.799992,6001.876262,5950.335251,5898.042302,5847.675511,5796.543563,5741.443815,5684.597475,5629.008258,5580.121147,5536.025881,5495.629406,5456.531057,5419.432093,5381.39263,5344.964945,5307.471515,5272.287292,5237.151761,5204.087811,5172.047914,5142.027145,5112.015012,5083.808431,5056.964689,5031.754624,5008.143863,4985.179697,4965.064712,4944.248882,4924.062719,4902.46232,4882.505008,4862.247234,4842.734536

where the values are raw values which didnt have baseline corrected when i am trying to correct baseline using zhang fit it is showing as tilted curve. Is there anything can you help to make the curve corrected or any suggestion is good enough.
![image](https://user-images.githubusercontent.com/40719582/215430069-36cd4627-1c63-4995-9666-bb1b2b6604f1.png)

**Comment by StatguyUser** [comment]
All I can say is that this could be an inherent property of the algorithm. As per the algorithm, this is a correct graph. You might want to try other algorithms for comparison purposes.
