### ISSUE TITLE
ImportError: cannot import name 'BaselineRemoval' from partially initialized module 'BaselineRemoval'

### ISSUE THREAD

**Issue by TzurV** [StatguyUser/BaselineRemoval#19]
Getting the following error from the following code:

``` 
import pandas as pd
import numpy as np
from BaselineRemoval import BaselineRemoval
import matplotlib.pyplot as plt
````

**Comment by TzurV** [comment]
It looks like the error happens just with Jupyter environment.

**Comment by StatguyUser** [comment]
I have tested this in multiple environments and is not an issue with the library.

**Comment by TzurV** [comment]
Thanks for looking into it. My mistake.

**Comment by StatguyUser** [comment]
No worries! Hope you find the library useful. 🤝🏻
