### ISSUE TITLE
While performing the Baseline Removal the code cell is showing "Max Iteration Reached"

### ISSUE THREAD

**Issue by ajinkyaanjikar30** [StatguyUser/BaselineRemoval#21]
I am using the library for a while now but the error I am getting is new as given in the title.
What does it mean? Is the library performing execution or not? Can I go on with the results obtained after baseline removal?

**Comment by X1nyuLu** [comment]
These algorithms need some loops to get the optial baseline. And there are two condition to The algorithm ends the loop in 2 cases. Firstly, the baseline is good enough (the error is smaller than the specific threshold). Second case is "Max Iteration Reached",  which means the number of loops reached the threshold setted by user but the iterated baseline is not good enough. So it runs well and you can use the result or modify the initial loop times.

**Comment by StatguyUser** [comment]
Ajinkya - As rightly pointed by @X1nyuLu, you need to modify the initial loop times.
