### ISSUE TITLE
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

### ISSUE THREAD

**Issue by X1nyuLu** [StatguyUser/BaselineRemoval#23]
the version of numpy and python is 1.26 and 3.10 respectively.
when i ran the example in readme, i got following error:

TypeError            Traceback (most recent call last)
......
File [~/miniconda3/envs/xxx/lib/python3.10/site-packages/BaselineRemoval.py:49](https://vscode-remote+ssh-002dremote-002bgitlab.vscode-resource.vscode-cdn.net/home/room/xxx/xxx/samples/~/miniconda3/envs/xxx/lib/python3.10/site-packages/BaselineRemoval.py:49), in BaselineRemoval.ModPoly(self, degree, repitition, gradient)
     46 yold=self.input_array
     47 yorig=self.input_array
---> 49 polx=self.poly(list(range(1,len(yorig)+1)),degree)
     50 nrep=0
     52 while (criteria>=gradient) and (nrep<=repitition):

File [~/miniconda3/envs/xx/lib/python3.10/site-packages/BaselineRemoval.py:27](https://vscode-remote+ssh-002dremote-002bgitlab.vscode-resource.vscode-cdn.net/home/room/xxx/xxx/samples/~/miniconda3/envs/xxx/lib/python3.10/site-packages/BaselineRemoval.py:27), in BaselineRemoval.poly(self, input_array_for_poly, degree_for_poly)
     18 '''qr factorization of a matrix. q` is orthonormal and `r` is upper-triangular.
     19 - QR decomposition is equivalent to Gram Schmidt orthogonalization, which builds a sequence of orthogonal polynomials that approximate your function with minimal least-squares error
     20 - in the next step, discard the first column from above matrix.
   (...)
     24 - concatenate all of these arrays created through loop, as a master array. This is done through (np.vstack)
     25 - transpose the master array, so that its more like a tabular form(np.transpose)'''
     26 input_array_for_poly = np.array(input_array_for_poly,dtype='object')
---> 27 X = np.transpose(np.vstack((input_array_for_poly**k for k in range(degree_for_poly+1))))
     28 return np.linalg.qr(X)[0][:,1:]
...
--> 209         raise TypeError('arrays to stack must be passed as a "sequence" type '
    210                         'such as list or tuple.')
    212     return tuple(arrays)

TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.
`

Then, i modify the **27th line in BaselineRemoval.py** from
 `X = np.transpose(np.vstack((input_array_for_poly**k for k in range(degree_for_poly+1))))` 
to `X = np.transpose(np.vstack([input_array_for_poly**k for k in range(degree_for_poly+1)]))`
and it finally works.

**Comment by StatguyUser** [comment]
Thank you for identifying and providing the solution. I have fixed it in the latest release 0.1.6.
