### ISSUE TITLE
Different baselines on different operating systems

### ISSUE THREAD

**Issue by KatPags** [StatguyUser/BaselineRemoval#8]
Hello, 

I am using your code to baseline some Raman spectra that I have. Running it on my Macbook results in different baselining to when I run it on a Windows PC. I am using identical code and identical data (have triple checked this) so am unsure what the issue is. 

I have attached images of the results from both systems.
![Mac Baselining](https://user-images.githubusercontent.com/101132313/158641049-91bf37e2-312c-45fc-b4d8-c578c4b19815.png)
![Windows Baselining](https://user-images.githubusercontent.com/101132313/158641068-e1bff37f-0c0e-47f6-b9ed-22671cc26687.png)

Thank you.

**Comment by StatguyUser** [comment]
Will definitely try to help you. Can you please import numpy, Sklearn and Scipy and check the version on both Mac and Windows? 

import numpy as np
import sklearn
import scipy

print(np.__version__)
print(sklearn.__version__)
print(scipy.__version__)

Let me know and we will try to fix the issue.

**Comment by KatPags** [comment]
Thank you for such a rapid response.

On my MacBook the version of numpy, sklearn and scipy are 1.20.2, 0.0 and 1.1.0
On my Windows PC they are 1.16.5, 0.0 and 1.3.1

Thank you.

**Comment by StatguyUser** [comment]
Can you please install Scipy, Sklearn and numpy of same version in your machine. Once done, restart your python to refresh it and then execute in both machine to compare? Let me know if you are still facing this issue.

**Comment by StatguyUser** [comment]
As a side note, it seems that issue is with ModPoly and IModpoly. Zhangfit results look same. Is my assumption correct or this issue exists for Zhangfit too?

**Comment by KatPags** [comment]
Will do.

And yes, the issue only seems to be with ModPoly and IModpoly

**Comment by StatguyUser** [comment]
If the issue still persists, I will try to set up a zoom call to debug and fix. In case same version of library doesn't help, Please suggest your time zone and availability for Friday and/or weekend.

**Comment by StatguyUser** [comment]
A few observations. 

Numpy 1.16.5 was released on Aug 28, 2019
Scipy 1.1.0 was  May 5, 2018

I will request you to update numpy, scipy and sklearn for the latest version.

pip install numpy --upgrade
pip install scipy --upgrade
pip install scikit-learn --upgrade

and then check if version are similar in both machine. If not, then install most latest version of the libraries. Once done, re-start your python to refresh latest library. Finally, re-run and compare output.

If its still giving you trouble, please suggest your timezone and availability for the week for scheduling a zoom call to live debug.

**Comment by KatPags** [comment]
Thank you, I will try this and let you know if it works.

**Comment by StatguyUser** [comment]
Can you please share the data? I will like to fix this issue.

**Comment by StatguyUser** [comment]
This issue has now been identified and fixed. The source of error was coming from line `np.array(input_array_for_poly)`. In Linux, np.array returns numpy array in numpy.int64 format, whereas for Windows, np.array returns the array in np.int32 format. This is where results were differing. In some cases, int64 was also insufficient. Hence, default data type is now set to `dtype=np.object`
